# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build
on:
  push:
    branches:
      - 'release'
  workflow_dispatch:
    inputs:
      tag:
        required: true
        default: false
        type: boolean
        description: Whether to tag the release

permissions:
  contents: write

jobs:
  build:
    name: Build
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-build.yml@trunk
    with:
      tag: ${{ github.event_name != 'workflow_dispatch' && true || github.event.inputs.tag }}
